name: Manual

concurrency:
  group: modern-test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: 'Test Rspack Version Tag'
        required: true
        default: 'latest'
        options:
        - canary
        - test
        - latest
jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: npm install -g pnpm@7.29.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: 🚀 Run Modern.js Test
        run: pnpm run test:modern --tag ${{ github.event.inputs.version }}
